H_WALL = "═"
V_WALL = "║"
TL_CORNER = "╔"
TR_CORNER = "╗"
BL_CORNER = "╚"
BR_CORNER = "╝"
T_DOOR = BR_CORNER+" "+BL_CORNER
B_DOOR = TR_CORNER+" "+TL_CORNER
L_DOOR = BR_CORNER+"\n"+TR_CORNER
R_DOOR = BL_CORNER+"\n"+TL_CORNER

T_BLOCKED = H_WALL*3
B_BLOCKED = H_WALL*3
L_BLOCKED = V_WALL*3
R_BLOCKED = V_WALL*3